### ISSUE TITLE
Unable to bundle using rollup

### ISSUE THREAD

**Issue by SimenB** [jonschlinkert/use#11]
See https://github.com/micromatch/micromatch/issues/107 and https://github.com/jonschlinkert/class-utils/issues/3.

Repro: https://github.com/SimenB/micromatch-rollup

This is blocking Jest from upgrading to micromatch 3

**Comment by jonschlinkert** [comment]
Since this library doesn't have the line of code you referenced in the log, I'm guessing it's an older version of this lib, which means it's probably used in an older version of snapdragon (which is used by micromatch).  

I will try to get this fixed so you don't need to deal with it, but this is really a bug in how rollup statically analyzes files.

**Comment by SimenB** [comment]
Yeah, snapdragon depends on version 2.

https://github.com/SimenB/micromatch-rollup/blob/ac567eaaf571f4cbc49ce3f392cd9aa3ecf64bba/yarn.lock#L764-L770

Thanks for looking into it!

**Comment by SimenB** [comment]
I'm still unable to bundle up micromatch (just updated all deps in the repro), but I'm guessing I have to wait for the update mantioned in here-be/snapdragon#12?

**Comment by SimenB** [comment]
Works now :tada:
